services:
  minio:
    container_name: minio_bucket
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET_NAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 5s
    expose:
      - "9000:9000"

  postgres:
    container_name: postgres_database
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      TZ: UTC
      PGTZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    expose:
      - "5433:5432"

  backend:
    container_name: backend_go
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        REPO_URL_BACKEND: ${REPO_URL_BACKEND}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BUCKET_NAME: "${MINIO_BUCKET_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1941/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${API_CONFIG_FILE_PATH:-/dev/null}:/app/configs/config.json

  frontend:
    container_name: frontend_react
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "${VITE_API_URL}"
        REPO_URL_FRONT: ${REPO_URL_FRONT}
    ports:
      - "443:443"

    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./cert/privkey.pem:/etc/ssl/private/privkey.pem:ro

volumes:
  minio_data:
  postgres_data: